# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"\x96\x01\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x13\n\x0bphoneNumber\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\x12\x14\n\x0creferralCode\x18\x07 \x01(\t\x12\r\n\x05token\x18\x08 \x01(\t\"\xa4\x01\n\x12\x43reateUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x13\n\x0bphoneNumber\x18\x05 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\t\x12\x14\n\x0creferralCode\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\"\x1e\n\rErrorResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t2^\n\x0bUserService\x12O\n\nCreateUser\x12\x1f.user_service.CreateUserRequest\x1a .user_service.CreateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=37
  _globals['_CREATEUSERREQUEST']._serialized_end=187
  _globals['_CREATEUSERRESPONSE']._serialized_start=190
  _globals['_CREATEUSERRESPONSE']._serialized_end=354
  _globals['_ERRORRESPONSE']._serialized_start=356
  _globals['_ERRORRESPONSE']._serialized_end=386
  _globals['_USERSERVICE']._serialized_start=388
  _globals['_USERSERVICE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
