[build]
  functions = "netlify/functions"  # Путь к папке с функциями
  publish = "public"               # Путь к папке со статическими файлами (если есть)

[dev]
  port = 8888                      # Порт, на котором будет запущен локальный сервер
