[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[functions.getUsers]
  timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
